library(conflicted)
library(terra)
library(tidyverse)
## library(dismo)
library(raster)
library(rgbif)
library(countrycode)
library(CoordinateCleaner)
library(rnaturalearthdata)
library(MASS)
library(blockCV)
library(flexsdm)
library(parallel)
library(ggokabeito)
library(ggpubr)
library(pROC)
library(wesanderson)
library(ggnewscale)
library(tidyterra)
## library(ENMeval)
library(virtualspecies)
library(ade4)
library(patchwork)
## library(neotoma2)
library(auk)
library(faux)
library(biscale)
library(spMaps)
library(mgcv)


conflict_prefer("filter", "dplyr")
conflicts_prefer(dplyr::filter)
conflict_prefer("select", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer("extract", "terra")
conflict_prefer("mutate", "dplyr")
conflict_prefer("intersect", "terra")
